#! /bin/bash

awk 'NR % 10 == 2 { print $1 " " $3  " " $5 " " $7}' report.txt > memory_change
awk 'NR % 10 == 3 { print $1 " " $3  " " $5 " " $7}' report.txt > swap_change
awk 'NR % 10 == 0 { print ($1 * 64 / 1000000 )}' report.log > report_change


