#! /bin/bash
dd if=/dev/zero of=outputFile bs=1G count=1                                                                             
                                                                          
