#! /bin/bash
echo $$ 
sync; echo 3 > sudo /proc/sys/vm/drop_caches
k=0
ns=$(( ($k+1)*1024*1024*1024 )) 
while [ $ns -lt $1 ]
do
	dd if=outputFile of=bufffff bs=1G count=1 >& heh
	k=k+1
	ns=$(( ($k+1)*1024*1024*1024 ))
done
ost=$(( $1-($k*(1024*1024*1024)) ))
dd if=outputFile of=bufffff bs=$ost count=1 >& heh
echo "Complite"
while true; do
	a=1+1
done
